baseURL = "https://hugo-c1e.pages.dev/"
title = "Allworldg Blog"
theme = "hugo-coder"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true 
cleanDestinationDir = true # clean obsolete or unrelated static file

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Allworldg"
description = "Allworldg's personal website"
keywords = "blog,developer,personal"
info = ["一个菜鸟小白的个人空间"]
avatarURL = "images/dog.png"
dateFormat = "2006-01-02"
since = 2022
colorScheme = "auto"
hideColorSchemeToggle = false

[params.utterances]
issueTerm = "pathname"
repo = "allworldg/hugo"
theme = "github-light"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/allworldg/"

[languages]
      [languages.zh-cn.menu]
          [[languages.zh-cn.menu.main]]
              name = "技术"
              weight = 1
              url  = "dev/"
          [[languages.zh-cn.menu.main]]
              name = "随笔"
              weight = 2
              url  = "essay/"
          [[languages.zh-cn.menu.main]]
              name = "学习"
              weight = 3
              url = "learn/"
          [[languages.zh-cn.menu.main]]
              name = "关于"
              weight = 4
              url  = "about/"
          


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4